version: '3'

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    networks:
      - inception
    ports:
      - "443:443"
    env_file:
      - .env
    restart: always

networks:
  inception:
    driver: bridge
