version: "3"

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    volumes:
      - db_volume:/var/lib/mysql/
    networks:
      - inception
    # expose:
    #   - 3306
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: on-failure

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
          condition: service_healthy
    volumes:
      - wp_volume:/var/www/html/
    networks:
      - inception
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "wp", "db", "check", "--allow-root" ]
      interval: 30s
      timeout: 5s
      retries: 3
    restart: on-failure

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    depends_on:
      wordpress:
        condition: service_healthy
    volumes:
      - wp_volume:/var/www/html/
    networks:
      - inception
    ports:
      - "443:443"
    env_file:
      - .env
    restart: on-failure

  redis:
    container_name: redis
    build: ./requirements/redis/
    networks:
      - inception
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: on-failure

  adminer:
    container_name: adminer
    build: ./requirements/adminer/
    depends_on:
      - wordpress
      - mariadb
    networks:
      - inception
    env_file:
      - .env
    ports:
      - "8080:8080"
    restart: on-failure

  website:
#    maybe need to add to inception network
    container_name: website
    build: ./requirements/website/
    ports:
      - "8081:8000"
    env_file:
      - .env
    restart: on-failure

  ftp:
    container_name: ftp
    build: ./requirements/ftp/
    depends_on:
      - wordpress
    volumes:
      - wp_volume:/var/www/html/
    networks:
      - inception
    env_file:
      - .env
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    restart: on-failure

#  mailhog:
#    container_name: mailhog
#    build: ./requirements/mailhog/
#    ports:
#      - "1025:1025"
#      - "8025:8025"
#    restart: on-failure

volumes:
  wp_volume:
    driver: local
    driver_opts:
      device: /home/${USER}/data/wordpress
      o: bind
      type: none

  db_volume:
    driver: local
    driver_opts:
      device: /home/${USER}/data/mariadb
      o: bind
      type: none

networks:
  inception:
    driver: bridge
