version: '3'

services:
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/
    # depends_on:
    #   - mariadb
    volumes:
      - wp_volume:/var/www/html/
    networks:
      - inception
    env_file:
      - .env
    restart: always

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    depends_on:
      - wordpress
    volumes:
      - wp_volume:/var/www/html/
    networks:
      - inception
    ports:
      - "443:443"
      - "80:80"
    env_file:
      - .env
    restart: always

volumes:
  wp_volume:
    driver: local
    driver_opts:
      device: /home/yuhayrap/data/wordpress
      o: bind
      type: none

networks:
  inception:
    driver: bridge
