version: "3"

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    volumes:
      - db_volume:/var/lib/mysql/
    networks:
      - db_network
    env_file:
      - .env
    restart: on-failure

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/
    depends_on:
      - mariadb
    volumes:
      - wp_volume:/var/www/html/
    networks:
      - db_network
    env_file:
      - .env
    restart: on-failure

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    depends_on:
      - wordpress
    volumes:
      - wp_volume:/var/www/html/
    networks:
      - db_network
    ports:
      - "443:443"
      - "80:80"
    env_file:
      - .env
    restart: on-failure

volumes:
  wp_volume:
    driver: local
    driver_opts:
      device: /home/${USER}/data/wordpress
      o: bind
      type: none
  db_volume:
    driver: local
    driver_opts:
      device: /home/${USER}/data/mariadb
      o: bind
      type: none

networks:
  db_network:
    driver: bridge
